# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import show.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBackground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u80cc\u666f\u540d')),
                ('img_upload', models.ImageField(storage=show.storage.BackgroundStorage(), upload_to=b'background', verbose_name='\u56fe\u7247\u4e0a\u4f20\u8def\u5f84')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_upload', models.ImageField(storage=show.storage.ImageStorage(), upload_to=b'img/%Y/%m/%d', verbose_name='\u56fe\u7247\u4e0a\u4f20\u8def\u5f84')),
                ('img_title', models.CharField(max_length=100, unique=True, verbose_name='\u56fe\u7247\u6807\u9898')),
                ('img_context', models.TextField(blank=True, max_length=100, null=True, verbose_name='\u56fe\u7247\u4ecb\u7ecd')),
                ('like_count', models.IntegerField(default=0, verbose_name='\u56fe\u7247\u559c\u6b22\u6b21\u6570')),
                ('img_create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u56fe\u7247\u53d1\u5e03\u65f6\u95f4')),
                ('img_update_time', models.DateTimeField(auto_now=True, verbose_name='\u56fe\u7247\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u76f8\u518c\u540d')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='img_group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='show.PhotoGroup'),
        ),
        migrations.AddField(
            model_name='photo',
            name='img_tags',
            field=models.ManyToManyField(blank=True, to='show.Tag'),
        ),
    ]
