# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='display',
            field=models.BooleanField(default=True, verbose_name='\u9690\u85cf'),
        ),
    ]
