# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-30 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='\u70b9\u8d5e\u6570'),
        ),
    ]
